# GitHub Super Linter Workflow
# This workflow will run the Super Linter on pull requests to ensure code quality

name: Super Linter

# Run this workflow on pull request events
on:
  pull_request:
    branches:
      - main
      - master
      - develop
    # Optional: Run on specific file changes
    # paths:
    #   - '**.js'
    #   - '**.ts'
    #   - '**.py'
    #   - '**.yml'
    #   - '**.yaml'

# Set permissions for the workflow
permissions:
  contents: read
  statuses: write
  pull-requests: write

jobs:
  super-lint:
    name: Super Linter
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get list of changed files
          fetch-depth: 0
          ref: jst-lint-demo
          
      # Run Super Linter
      - name: Run Super Linter
        uses: super-linter/super-linter@v5.7.2
        env:
          # Set the default branch for comparison
          DEFAULT_BRANCH: main
          
          # GitHub token for API access
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          # Only lint files that have changed in the PR
          VALIDATE_ALL_CODEBASE: false
          
          # Disable specific linters that can be problematic or noisy
          # All other linters will run by default
          VALIDATE_JSCPD: false                    # Disable copy-paste detection (can be noisy)
          VALIDATE_KUBERNETES_KUBECONFORM: false   # Disable if you don't use Kubernetes
          VALIDATE_NATURAL_LANGUAGE: false        # Disable natural language linting (can be noisy)
          VALIDATE_CHECKOV: false                  # Disable Checkov (can be resource intensive)
          VALIDATE_GITLEAKS: false                 # Disable GitLeaks (may cause issues in some repos)
          VALIDATE_TEKTON: false                   # Disable if you don't use Tekton
          VALIDATE_ARM: false                      # Disable if you don't use Azure ARM templates
          
          # Optional: Suppress specific linters for certain paths
          # FILTER_REGEX_EXCLUDE: '.*/(node_modules|\.git)/.*'
          
          # Optional: Set log level (ERROR, WARN, INFO, DEBUG)
          LOG_LEVEL: INFO
          
          # Optional: Create annotations on PR
          CREATE_LOG_FILE: true
